# Generated by Django 5.0.1 on 2024-01-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organization_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('offer_requirements', models.CharField(max_length=300)),
                ('employment_type', models.CharField(max_length=100)),
                ('salary', models.FloatField(default='Não informado')),
                ('organization_description', models.TextField()),
            ],
        ),
    ]
