# Generated by Django 5.0.1 on 2024-01-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_joboffer_recruiter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='recruiter_email',
            field=models.EmailField(editable=False, max_length=254),
        ),
    ]
