# Generated by Django 5.0.1 on 2024-01-22 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_joboffer_number_of_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListingCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_offers', models.IntegerField()),
            ],
        ),
    ]
