# Generated by Django 5.0.1 on 2024-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_joblistingcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
