# Generated by Django 5.0.1 on 2024-06-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_joboffer_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='allowed',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
