# Generated by Django 5.0.1 on 2024-06-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_joboffer_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='company_site',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
