version: "3.9"

services:

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  web:
    build:
      context: .
    container_name: django_app
    restart: always
    environment:
      DB_NAME: my_db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_PORT: 5432
      DB_HOST: db
    volumes:
      - ./static:/app/static
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
